language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - black --check blogging mysite polling --exclude="blogging/migrations/"
  - python manage.py test